### ISSUE TITLE
TypeError: this.stream.clearLine is not a function

### ISSUE THREAD

**Issue by straxhaber** [qqilihq/partial-emlx-converter#29]
I'm getting the following error when I run it:

```
TypeError: this.stream.clearLine is not a function
    at ProgressBar.interrupt (/usr/local/Cellar/partial-emlx-converter/3.0.2/libexec/lib/node_modules/partial-emlx-converter/node_modules/progress/lib/node-progress.js:210:15)
    at processEmlxs (/usr/local/Cellar/partial-emlx-converter/3.0.2/libexec/lib/node_modules/partial-emlx-converter/dist/converter.js:26:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by qqilihq** [comment]
Any details about the environment you're running this in?

**Comment by straxhaber** [comment]
My bad for not including that! macOS 12.1, installed via Homebrew, run on the V9 Mail Library that is standard with macOS. is there any other environment you would like to know? I really appreciate your help :) Getting this to work is super important to me.

**Comment by qqilihq** [comment]
Thanks, this helps. I have located the issue and will provide a fix soon.

**Comment by qqilihq** [comment]
This should now be fixed with [v3.0.3](https://github.com/qqilihq/partial-emlx-converter/blob/master/changelog.md#303--2022-01-02). Can you give it a try and let me know? (it's also available via homebrew)

**Comment by qqilihq** [comment]
@straxhaber Any feedback?

**Comment by qqilihq** [comment]
@straxhaber Ping
