### ISSUE TITLE
Missing line break after boundary string lets conversion fail

### ISSUE THREAD

**Issue by yuergen** [qqilihq/partial-emlx-converter#5]
For some messages I am converting I get errors like this one:
```
(node:8919) UnhandledPromiseRejectionWarning: Error: Different boundary strings (expected '===============7980816086339553567==', got: '===============7980816086339553567==-')
    at parts.forEach.part (/home/juergen/github/partial-emlx-converter/build/src/converter.js:76:19)
    at Array.forEach (<anonymous>)
    at writeBody (/home/juergen/github/partial-emlx-converter/build/src/converter.js:69:11)
    at emlformat.parse (/home/juergen/github/partial-emlx-converter/build/src/converter.js:52:17)
    at Object.emlformat.parse (/home/juergen/github/partial-emlx-converter/node_modules/eml-format/lib/eml-format.js:554:5)
    at Promise (/home/juergen/github/partial-emlx-converter/build/src/converter.js:45:19)
    at new Promise (<anonymous>)
    at processEmlx (/home/juergen/github/partial-emlx-converter/build/src/converter.js:44:12)
    at /home/juergen/github/partial-emlx-converter/build/src/converter.js:30:38
    at Generator.next (<anonymous>)
(node:8919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:8919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This following excerpt is from the emlx file:
```
--===============7980816086339553567==-<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
```

Other mails look like this:
```
--===============7104596152329226118==--
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
```

The missing line break seems to be the culprit.

**Comment by qqilihq** [comment]
Thanks. Any chance you could supply me with a test file (I'd understand that this might be difficult due to privacy concerns, but I thought I just ask).

I'll try to have a look at this one -- those boundaries in combination with newlines gave me quite some headache during development :-)

**Comment by yuergen** [comment]
Thank you for your reply. I will supply you with the smallest sample I can find in my archive.

However the missing line break is always at the end of the emlx file between the boundary and the XML start:
```
_______________________________________________
Some mailing list
address@example.com
http://example.com/mailman/listinfo/somemailinglist

--===============3331787384868445895==-<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>date-received</key>
	<integer>1346074997</integer>
	<key>date-sent</key>
	<integer>1346074997</integer>
	<key>flags</key>
	<integer>8590195713</integer>
	<key>original-mailbox</key>
	<string>imap://someserver</string>
	<key>remote-id</key>
	<string>10916</string>
	<key>sender</key>
	<string>Joe &lt;joe@example.com&gt;</string>
	<key>subject</key>
	<string>Some mail</string>
	<key>to</key>
	<string>Alice &lt;alice@example.com&gt;</string>
</dict>
</plist>
```

**Comment by qqilihq** [comment]
I've just been investigating this, and I'm a little surprised that the boundary string before the XML only ends with a single `-`. According to the spec, the close delimiter is supposed to look like this:

```
close-delimiter := delimiter "--"
```

Out of curiosity: Is this the case with many of your emails? Are they all from a mailing list or does this happen with other emails as well?

**Comment by yuergen** [comment]
Every time the conversion fails, I move the offending mail out of the source folders. I am still not done with this.

Searching for "==-<" gives me 23 results in the rejects folder.

If I am not mistaken all mails are related to mailing lists managed by mailman.
